
  spring:
    config:
      activate:
        on-profile: docker

    datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-user:5432/user_db}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:maria}
      driver-class-name: org.postgresql.Driver

      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 2000000
        connection-timeout: 30000
        initialization-fail-timeout: 60000

    jpa:
      hibernate:
        ddl-auto: update

      show-sql: false

      database-platform: org.hibernate.dialect.PostgreSQLDialect

      properties:
        hibernate:
          format_sql: true

    kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

      consumer:
        group-id: user-service-group
        auto-offset-reset: earliest

    jackson:
      time-zone: America/Sao_Paulo


  server:
    port: 8001


  jwt:
    secret: ${JWT_SECRET:dev-secret-super-long-for-hs256-algo-1234567890}

    expiration: ${JWT_EXPIRATION:3600000}


  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.apache.kafka: WARN
      org.hibernate.SQL: DEBUG
