spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-tx:5432/tx_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:maria}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: transaction-service-group
      auto-offset-reset: earliest

external:
  brasilapi:
    url: ${BRASILAPI_URL:https://brasilapi.com.br/api}
  mockbank:
    url: ${MOCKBANK_URL:http://mockbank:8080} # 🔥 ajuste importante para docker

jwt:
  secret: ${JWT_SECRET:dev-secret-123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:3600000}

server:
  port: 8002

logging:
  level:
    org.springframework: INFO
    org.apache.kafka: WARN