server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:replace_with_secure_secret}

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: ${USER_SERVICE_URL:http://user:8001}
          predicates:
            - Path=/users/**
            - Path=/auth/**

        - id: transaction
          uri: ${TX_SERVICE_URL:http://transaction-service:8002}
          predicates:
            - Path=/transactions/**
            - Path=/balance/**

        - id: analytics
          uri: ${ANALYTICS_SERVICE_URL:http://analytics-service:8003}
          predicates:
            - Path=/analytics/**